import { movies } from "./movies";
import { Sala } from "../Types/RoomType";

export const Salas:Sala[] = [
    {
        id:1,
        filme:movies[0],
        cronogramas:[
            {
                horario: "19:00",
                cadeiras: [
                  {id: 1, status: "livre"},
                  {id: 2, status: "ocupado"},
                  {id: 3, status:"livre"},
                  {id: 4, status: "livre"},
                  {id: 5, status: "livre"},
                  {id: 6, status: "ocupado"},
                  {id: 7, status: "ocupado"},
                  {id: 8, status: "ocupado"},
                  {id: 9, status: "livre"},
                  {id: 10, status: "ocupado"},
                  {id: 11, status: "ocupado"},
                  {id: 12, status: "ocupado"},
                  {id: 13, status: "livre"},
                  {id: 14, status: "livre"},
                  {id: 15, status: "livre"},
                  {id: 16, status: "ocupado"},
                  {id: 17, status: "livre"},
                  {id: 18, status: "livre"},
                  {id: 19, status: "ocupado"},
                  {id: 20, status: "livre"},
                  {id: 21, status: "ocupado"},
                  {id: 22, status: "ocupado"},
                  {id: 23, status: "ocupado"},
                  {id: 24, status: "livre"},
                  {id: 25, status: "livre"},
                  {id: 26, status: "livre"},
                  {id: 27, status: "livre"},
                  {id: 28, status: "livre"},
                  {id: 29, status: "ocupado"},
                  {id: 30, status: "ocupado"},
                  
                ]
            },
            {
                horario: "20:30",
                cadeiras: [
                    {id: 1, status: "livre"},
                    {id: 2, status: "ocupado"},
                    {id: 3, status:"livre"},
                    {id: 4, status: "livre"},
                    {id: 5, status: "livre"},
                    {id: 6, status: "ocupado"},
                    {id: 7, status: "ocupado"},
                    {id: 8, status: "ocupado"},
                    {id: 9, status: "livre"},
                    {id: 10, status: "ocupado"},
                    {id: 11, status: "ocupado"},
                    {id: 12, status: "ocupado"},
                    {id: 13, status: "livre"},
                    {id: 14, status: "livre"},
                    {id: 15, status: "livre"},
                    {id: 16, status: "ocupado"},
                    {id: 17, status: "livre"},
                    {id: 18, status: "livre"},
                    {id: 19, status: "ocupado"},
                    {id: 20, status: "livre"},
                    {id: 21, status: "ocupado"},
                    {id: 22, status: "ocupado"},
                    {id: 23, status: "ocupado"},
                    {id: 24, status: "livre"},
                    {id: 25, status: "livre"},
                    {id: 26, status: "livre"},
                    {id: 27, status: "livre"},
                    {id: 28, status: "livre"},
                    {id: 29, status: "ocupado"},
                    {id: 30, status: "ocupado"},
                    
                ]
            },
            {
                horario: "22:30",
                cadeiras: [
                    {id: 1, status: "livre"},
                    {id: 2, status: "ocupado"},
                    {id: 3, status:"livre"},
                    {id: 4, status: "livre"},
                    {id: 5, status: "livre"},
                    {id: 6, status: "ocupado"},
                    {id: 7, status: "ocupado"},
                    {id: 8, status: "ocupado"},
                    {id: 9, status: "livre"},
                    {id: 10, status: "ocupado"},
                    {id: 11, status: "ocupado"},
                    {id: 12, status: "ocupado"},
                    {id: 13, status: "livre"},
                    {id: 14, status: "livre"},
                    {id: 15, status: "livre"},
                    {id: 16, status: "ocupado"},
                    {id: 17, status: "livre"},
                    {id: 18, status: "livre"},
                    {id: 19, status: "ocupado"},
                    {id: 20, status: "livre"},
                    {id: 21, status: "ocupado"},
                    {id: 22, status: "ocupado"},
                    {id: 23, status: "ocupado"},
                    {id: 24, status: "livre"},
                    {id: 25, status: "livre"},
                    {id: 26, status: "livre"},
                    {id: 27, status: "livre"},
                    {id: 28, status: "livre"},
                    {id: 29, status: "ocupado"},
                    {id: 30, status: "ocupado"},
                    
                ]
            }
        ]
    },
    {
        id:2,
        filme:movies[1],
        cronogramas:[
            {
                horario: "19:00",
                cadeiras: [
                  {id: 1, status: "livre"},
                  {id: 2, status: "ocupado"},
                  {id: 3, status:"livre"},
                  {id: 4, status: "livre"},
                  {id: 5, status: "livre"},
                  {id: 6, status: "ocupado"},
                  {id: 7, status: "ocupado"},
                  {id: 8, status: "ocupado"},
                  {id: 9, status: "livre"},
                  {id: 10, status: "ocupado"},
                  {id: 11, status: "ocupado"},
                  {id: 12, status: "ocupado"},
                  {id: 13, status: "livre"},
                  {id: 14, status: "livre"},
                  {id: 15, status: "livre"},
                  {id: 16, status: "ocupado"},
                  {id: 17, status: "livre"},
                  {id: 18, status: "livre"},
                  {id: 19, status: "ocupado"},
                  {id: 20, status: "livre"},
                  {id: 21, status: "ocupado"},
                  {id: 22, status: "ocupado"},
                  {id: 23, status: "ocupado"},
                  {id: 24, status: "livre"},
                  {id: 25, status: "livre"},
                  {id: 26, status: "livre"},
                  {id: 27, status: "livre"},
                  {id: 28, status: "livre"},
                  {id: 29, status: "ocupado"},
                  {id: 30, status: "ocupado"},
                  
                ]
            },
            {
                horario: "20:30",
                cadeiras: [
                    {id: 1, status: "livre"},
                    {id: 2, status: "ocupado"},
                    {id: 3, status:"livre"},
                    {id: 4, status: "livre"},
                    {id: 5, status: "livre"},
                    {id: 6, status: "ocupado"},
                    {id: 7, status: "ocupado"},
                    {id: 8, status: "ocupado"},
                    {id: 9, status: "livre"},
                    {id: 10, status: "ocupado"},
                    {id: 11, status: "ocupado"},
                    {id: 12, status: "ocupado"},
                    {id: 13, status: "livre"},
                    {id: 14, status: "livre"},
                    {id: 15, status: "livre"},
                    {id: 16, status: "ocupado"},
                    {id: 17, status: "livre"},
                    {id: 18, status: "livre"},
                    {id: 19, status: "ocupado"},
                    {id: 20, status: "livre"},
                    {id: 21, status: "ocupado"},
                    {id: 22, status: "ocupado"},
                    {id: 23, status: "ocupado"},
                    {id: 24, status: "livre"},
                    {id: 25, status: "livre"},
                    {id: 26, status: "livre"},
                    {id: 27, status: "livre"},
                    {id: 28, status: "livre"},
                    {id: 29, status: "ocupado"},
                    {id: 30, status: "ocupado"},
                    
                ]
            },
            {
                horario: "21:30",
                cadeiras: [
                    {id: 1, status: "livre"},
                    {id: 2, status: "ocupado"},
                    {id: 3, status:"livre"},
                    {id: 4, status: "livre"},
                    {id: 5, status: "livre"},
                    {id: 6, status: "ocupado"},
                    {id: 7, status: "ocupado"},
                    {id: 8, status: "ocupado"},
                    {id: 9, status: "livre"},
                    {id: 10, status: "ocupado"},
                    {id: 11, status: "ocupado"},
                    {id: 12, status: "ocupado"},
                    {id: 13, status: "livre"},
                    {id: 14, status: "livre"},
                    {id: 15, status: "livre"},
                    {id: 16, status: "ocupado"},
                    {id: 17, status: "livre"},
                    {id: 18, status: "livre"},
                    {id: 19, status: "ocupado"},
                    {id: 20, status: "livre"},
                    {id: 21, status: "ocupado"},
                    {id: 22, status: "ocupado"},
                    {id: 23, status: "ocupado"},
                    {id: 24, status: "livre"},
                    {id: 25, status: "livre"},
                    {id: 26, status: "livre"},
                    {id: 27, status: "livre"},
                    {id: 28, status: "livre"},
                    {id: 29, status: "ocupado"},
                    {id: 30, status: "ocupado"},
                    
                ]
            }
        ]
    },
    {
        id:3,
        filme:movies[2],
        cronogramas:[
            {
                horario: "19:00",
                cadeiras: [
                  {id: 1, status: "livre"},
                  {id: 2, status: "ocupado"},
                  {id: 3, status:"livre"},
                  {id: 4, status: "livre"},
                  {id: 5, status: "livre"},
                  {id: 6, status: "ocupado"},
                  {id: 7, status: "ocupado"},
                  {id: 8, status: "ocupado"},
                  {id: 9, status: "livre"},
                  {id: 10, status: "ocupado"},
                  {id: 11, status: "ocupado"},
                  {id: 12, status: "ocupado"},
                  {id: 13, status: "livre"},
                  {id: 14, status: "livre"},
                  {id: 15, status: "livre"},
                  {id: 16, status: "ocupado"},
                  {id: 17, status: "livre"},
                  {id: 18, status: "livre"},
                  {id: 19, status: "ocupado"},
                  {id: 20, status: "livre"},
                  {id: 21, status: "ocupado"},
                  {id: 22, status: "ocupado"},
                  {id: 23, status: "ocupado"},
                  {id: 24, status: "livre"},
                  {id: 25, status: "livre"},
                  {id: 26, status: "livre"},
                  {id: 27, status: "livre"},
                  {id: 28, status: "livre"},
                  {id: 29, status: "ocupado"},
                  {id: 30, status: "ocupado"},
                  
                ]
            },
            {
                horario: "20:30",
                cadeiras: [
                    {id: 1, status: "livre"},
                    {id: 2, status: "ocupado"},
                    {id: 3, status:"livre"},
                    {id: 4, status: "livre"},
                    {id: 5, status: "livre"},
                    {id: 6, status: "ocupado"},
                    {id: 7, status: "ocupado"},
                    {id: 8, status: "ocupado"},
                    {id: 9, status: "livre"},
                    {id: 10, status: "ocupado"},
                    {id: 11, status: "ocupado"},
                    {id: 12, status: "ocupado"},
                    {id: 13, status: "livre"},
                    {id: 14, status: "livre"},
                    {id: 15, status: "livre"},
                    {id: 16, status: "ocupado"},
                    {id: 17, status: "livre"},
                    {id: 18, status: "livre"},
                    {id: 19, status: "ocupado"},
                    {id: 20, status: "livre"},
                    {id: 21, status: "ocupado"},
                    {id: 22, status: "ocupado"},
                    {id: 23, status: "ocupado"},
                    {id: 24, status: "livre"},
                    {id: 25, status: "livre"},
                    {id: 26, status: "livre"},
                    {id: 27, status: "livre"},
                    {id: 28, status: "livre"},
                    {id: 29, status: "ocupado"},
                    {id: 30, status: "ocupado"},
                    
                ]
            },
            {
                horario: "21:30",
                cadeiras: [
                    {id: 1, status: "livre"},
                    {id: 2, status: "ocupado"},
                    {id: 3, status:"livre"},
                    {id: 4, status: "livre"},
                    {id: 5, status: "livre"},
                    {id: 6, status: "ocupado"},
                    {id: 7, status: "ocupado"},
                    {id: 8, status: "ocupado"},
                    {id: 9, status: "livre"},
                    {id: 10, status: "ocupado"},
                    {id: 11, status: "ocupado"},
                    {id: 12, status: "ocupado"},
                    {id: 13, status: "livre"},
                    {id: 14, status: "livre"},
                    {id: 15, status: "livre"},
                    {id: 16, status: "ocupado"},
                    {id: 17, status: "livre"},
                    {id: 18, status: "livre"},
                    {id: 19, status: "ocupado"},
                    {id: 20, status: "livre"},
                    {id: 21, status: "ocupado"},
                    {id: 22, status: "ocupado"},
                    {id: 23, status: "ocupado"},
                    {id: 24, status: "livre"},
                    {id: 25, status: "livre"},
                    {id: 26, status: "livre"},
                    {id: 27, status: "livre"},
                    {id: 28, status: "livre"},
                    {id: 29, status: "ocupado"},
                    {id: 30, status: "ocupado"},
                    
                ]
            }
        ]
    },
    {
        id:4,
        filme:movies[3],
        cronogramas:[
            {
                horario: "19:00",
                cadeiras: [
                  {id: 1, status: "livre"},
                  {id: 2, status: "ocupado"},
                  {id: 3, status:"livre"},
                  {id: 4, status: "livre"},
                  {id: 5, status: "livre"},
                  {id: 6, status: "ocupado"},
                  {id: 7, status: "ocupado"},
                  {id: 8, status: "ocupado"},
                  {id: 9, status: "livre"},
                  {id: 10, status: "ocupado"},
                  {id: 11, status: "ocupado"},
                  {id: 12, status: "ocupado"},
                  {id: 13, status: "livre"},
                  {id: 14, status: "livre"},
                  {id: 15, status: "livre"},
                  {id: 16, status: "ocupado"},
                  {id: 17, status: "livre"},
                  {id: 18, status: "livre"},
                  {id: 19, status: "ocupado"},
                  {id: 20, status: "livre"},
                  {id: 21, status: "ocupado"},
                  {id: 22, status: "ocupado"},
                  {id: 23, status: "ocupado"},
                  {id: 24, status: "livre"},
                  {id: 25, status: "livre"},
                  {id: 26, status: "livre"},
                  {id: 27, status: "livre"},
                  {id: 28, status: "livre"},
                  {id: 29, status: "ocupado"},
                  {id: 30, status: "ocupado"},
                  
                ]
            },
            {
                horario: "20:30",
                cadeiras: [
                    {id: 1, status: "livre"},
                    {id: 2, status: "ocupado"},
                    {id: 3, status:"livre"},
                    {id: 4, status: "livre"},
                    {id: 5, status: "livre"},
                    {id: 6, status: "ocupado"},
                    {id: 7, status: "ocupado"},
                    {id: 8, status: "ocupado"},
                    {id: 9, status: "livre"},
                    {id: 10, status: "ocupado"},
                    {id: 11, status: "ocupado"},
                    {id: 12, status: "ocupado"},
                    {id: 13, status: "livre"},
                    {id: 14, status: "livre"},
                    {id: 15, status: "livre"},
                    {id: 16, status: "ocupado"},
                    {id: 17, status: "livre"},
                    {id: 18, status: "livre"},
                    {id: 19, status: "ocupado"},
                    {id: 20, status: "livre"},
                    {id: 21, status: "ocupado"},
                    {id: 22, status: "ocupado"},
                    {id: 23, status: "ocupado"},
                    {id: 24, status: "livre"},
                    {id: 25, status: "livre"},
                    {id: 26, status: "livre"},
                    {id: 27, status: "livre"},
                    {id: 28, status: "livre"},
                    {id: 29, status: "ocupado"},
                    {id: 30, status: "ocupado"},
                    
                ]
            },
            {
                horario: "21:30",
                cadeiras: [
                    {id: 1, status: "livre"},
                    {id: 2, status: "ocupado"},
                    {id: 3, status:"livre"},
                    {id: 4, status: "livre"},
                    {id: 5, status: "livre"},
                    {id: 6, status: "ocupado"},
                    {id: 7, status: "ocupado"},
                    {id: 8, status: "ocupado"},
                    {id: 9, status: "livre"},
                    {id: 10, status: "ocupado"},
                    {id: 11, status: "ocupado"},
                    {id: 12, status: "ocupado"},
                    {id: 13, status: "livre"},
                    {id: 14, status: "livre"},
                    {id: 15, status: "livre"},
                    {id: 16, status: "ocupado"},
                    {id: 17, status: "livre"},
                    {id: 18, status: "livre"},
                    {id: 19, status: "ocupado"},
                    {id: 20, status: "livre"},
                    {id: 21, status: "ocupado"},
                    {id: 22, status: "ocupado"},
                    {id: 23, status: "ocupado"},
                    {id: 24, status: "livre"},
                    {id: 25, status: "livre"},
                    {id: 26, status: "livre"},
                    {id: 27, status: "livre"},
                    {id: 28, status: "livre"},
                    {id: 29, status: "ocupado"},
                    {id: 30, status: "ocupado"},
                    
                ]
            }
        ]
    },
    {
        id:5,
        filme:movies[4],
        cronogramas:[
            {
                horario: "19:00",
                cadeiras: [
                  {id: 1, status: "livre"},
                  {id: 2, status: "ocupado"},
                  {id: 3, status:"livre"},
                  {id: 4, status: "livre"},
                  {id: 5, status: "livre"},
                  {id: 6, status: "ocupado"},
                  {id: 7, status: "ocupado"},
                  {id: 8, status: "ocupado"},
                  {id: 9, status: "livre"},
                  {id: 10, status: "ocupado"},
                  {id: 11, status: "ocupado"},
                  {id: 12, status: "ocupado"},
                  {id: 13, status: "livre"},
                  {id: 14, status: "livre"},
                  {id: 15, status: "livre"},
                  {id: 16, status: "ocupado"},
                  {id: 17, status: "livre"},
                  {id: 18, status: "livre"},
                  {id: 19, status: "ocupado"},
                  {id: 20, status: "livre"},
                  {id: 21, status: "ocupado"},
                  {id: 22, status: "ocupado"},
                  {id: 23, status: "ocupado"},
                  {id: 24, status: "livre"},
                  {id: 25, status: "livre"},
                  {id: 26, status: "livre"},
                  {id: 27, status: "livre"},
                  {id: 28, status: "livre"},
                  {id: 29, status: "ocupado"},
                  {id: 30, status: "ocupado"},
                  
                ]
            },
            {
                horario: "20:30",
                cadeiras: [
                    {id: 1, status: "livre"},
                    {id: 2, status: "ocupado"},
                    {id: 3, status:"livre"},
                    {id: 4, status: "livre"},
                    {id: 5, status: "livre"},
                    {id: 6, status: "ocupado"},
                    {id: 7, status: "ocupado"},
                    {id: 8, status: "ocupado"},
                    {id: 9, status: "livre"},
                    {id: 10, status: "ocupado"},
                    {id: 11, status: "ocupado"},
                    {id: 12, status: "ocupado"},
                    {id: 13, status: "livre"},
                    {id: 14, status: "livre"},
                    {id: 15, status: "livre"},
                    {id: 16, status: "ocupado"},
                    {id: 17, status: "livre"},
                    {id: 18, status: "livre"},
                    {id: 19, status: "ocupado"},
                    {id: 20, status: "livre"},
                    {id: 21, status: "ocupado"},
                    {id: 22, status: "ocupado"},
                    {id: 23, status: "ocupado"},
                    {id: 24, status: "livre"},
                    {id: 25, status: "livre"},
                    {id: 26, status: "livre"},
                    {id: 27, status: "livre"},
                    {id: 28, status: "livre"},
                    {id: 29, status: "ocupado"},
                    {id: 30, status: "ocupado"},
                    
                ]
            },
            {
                horario: "21:30",
                cadeiras: [
                    {id: 1, status: "livre"},
                    {id: 2, status: "ocupado"},
                    {id: 3, status:"livre"},
                    {id: 4, status: "livre"},
                    {id: 5, status: "livre"},
                    {id: 6, status: "ocupado"},
                    {id: 7, status: "ocupado"},
                    {id: 8, status: "ocupado"},
                    {id: 9, status: "livre"},
                    {id: 10, status: "ocupado"},
                    {id: 11, status: "ocupado"},
                    {id: 12, status: "ocupado"},
                    {id: 13, status: "livre"},
                    {id: 14, status: "livre"},
                    {id: 15, status: "livre"},
                    {id: 16, status: "ocupado"},
                    {id: 17, status: "livre"},
                    {id: 18, status: "livre"},
                    {id: 19, status: "ocupado"},
                    {id: 20, status: "livre"},
                    {id: 21, status: "ocupado"},
                    {id: 22, status: "ocupado"},
                    {id: 23, status: "ocupado"},
                    {id: 24, status: "livre"},
                    {id: 25, status: "livre"},
                    {id: 26, status: "livre"},
                    {id: 27, status: "livre"},
                    {id: 28, status: "livre"},
                    {id: 29, status: "ocupado"},
                    {id: 30, status: "ocupado"},
                    
                ]
            }
        ]
    },
    {
        id:6,
        filme:movies[5],
        cronogramas:[
            {
                horario: "19:00",
                cadeiras: [
                  {id: 1, status: "livre"},
                  {id: 2, status: "ocupado"},
                  {id: 3, status:"livre"},
                  {id: 4, status: "livre"},
                  {id: 5, status: "livre"},
                  {id: 6, status: "ocupado"},
                  {id: 7, status: "ocupado"},
                  {id: 8, status: "ocupado"},
                  {id: 9, status: "livre"},
                  {id: 10, status: "ocupado"},
                  {id: 11, status: "ocupado"},
                  {id: 12, status: "ocupado"},
                  {id: 13, status: "livre"},
                  {id: 14, status: "livre"},
                  {id: 15, status: "livre"},
                  {id: 16, status: "ocupado"},
                  {id: 17, status: "livre"},
                  {id: 18, status: "livre"},
                  {id: 19, status: "ocupado"},
                  {id: 20, status: "livre"},
                  {id: 21, status: "ocupado"},
                  {id: 22, status: "ocupado"},
                  {id: 23, status: "ocupado"},
                  {id: 24, status: "livre"},
                  {id: 25, status: "livre"},
                  {id: 26, status: "livre"},
                  {id: 27, status: "livre"},
                  {id: 28, status: "livre"},
                  {id: 29, status: "ocupado"},
                  {id: 30, status: "ocupado"},
                  
                ]
            },
            {
                horario: "20:30",
                cadeiras: [
                    {id: 1, status: "livre"},
                    {id: 2, status: "ocupado"},
                    {id: 3, status:"livre"},
                    {id: 4, status: "livre"},
                    {id: 5, status: "livre"},
                    {id: 6, status: "ocupado"},
                    {id: 7, status: "ocupado"},
                    {id: 8, status: "ocupado"},
                    {id: 9, status: "livre"},
                    {id: 10, status: "ocupado"},
                    {id: 11, status: "ocupado"},
                    {id: 12, status: "ocupado"},
                    {id: 13, status: "livre"},
                    {id: 14, status: "livre"},
                    {id: 15, status: "livre"},
                    {id: 16, status: "ocupado"},
                    {id: 17, status: "livre"},
                    {id: 18, status: "livre"},
                    {id: 19, status: "ocupado"},
                    {id: 20, status: "livre"},
                    {id: 21, status: "ocupado"},
                    {id: 22, status: "ocupado"},
                    {id: 23, status: "ocupado"},
                    {id: 24, status: "livre"},
                    {id: 25, status: "livre"},
                    {id: 26, status: "livre"},
                    {id: 27, status: "livre"},
                    {id: 28, status: "livre"},
                    {id: 29, status: "ocupado"},
                    {id: 30, status: "ocupado"},
                    
                ]
            },
            {
                horario: "21:30",
                cadeiras: [
                    {id: 1, status: "livre"},
                    {id: 2, status: "ocupado"},
                    {id: 3, status:"livre"},
                    {id: 4, status: "livre"},
                    {id: 5, status: "livre"},
                    {id: 6, status: "ocupado"},
                    {id: 7, status: "ocupado"},
                    {id: 8, status: "ocupado"},
                    {id: 9, status: "livre"},
                    {id: 10, status: "ocupado"},
                    {id: 11, status: "ocupado"},
                    {id: 12, status: "ocupado"},
                    {id: 13, status: "livre"},
                    {id: 14, status: "livre"},
                    {id: 15, status: "livre"},
                    {id: 16, status: "ocupado"},
                    {id: 17, status: "livre"},
                    {id: 18, status: "livre"},
                    {id: 19, status: "ocupado"},
                    {id: 20, status: "livre"},
                    {id: 21, status: "ocupado"},
                    {id: 22, status: "ocupado"},
                    {id: 23, status: "ocupado"},
                    {id: 24, status: "livre"},
                    {id: 25, status: "livre"},
                    {id: 26, status: "livre"},
                    {id: 27, status: "livre"},
                    {id: 28, status: "livre"},
                    {id: 29, status: "ocupado"},
                    {id: 30, status: "ocupado"},
                    
                ]
            }
        ]
    },
    {
        id:7,
        filme:movies[6],
        cronogramas:[
            {
                horario: "19:00",
                cadeiras: [
                  {id: 1, status: "livre"},
                  {id: 2, status: "ocupado"},
                  {id: 3, status:"livre"},
                  {id: 4, status: "livre"},
                  {id: 5, status: "livre"},
                  {id: 6, status: "ocupado"},
                  {id: 7, status: "ocupado"},
                  {id: 8, status: "ocupado"},
                  {id: 9, status: "livre"},
                  {id: 10, status: "ocupado"},
                  {id: 11, status: "ocupado"},
                  {id: 12, status: "ocupado"},
                  {id: 13, status: "livre"},
                  {id: 14, status: "livre"},
                  {id: 15, status: "livre"},
                  {id: 16, status: "ocupado"},
                  {id: 17, status: "livre"},
                  {id: 18, status: "livre"},
                  {id: 19, status: "ocupado"},
                  {id: 20, status: "livre"},
                  {id: 21, status: "ocupado"},
                  {id: 22, status: "ocupado"},
                  {id: 23, status: "ocupado"},
                  {id: 24, status: "livre"},
                  {id: 25, status: "livre"},
                  {id: 26, status: "livre"},
                  {id: 27, status: "livre"},
                  {id: 28, status: "livre"},
                  {id: 29, status: "ocupado"},
                  {id: 30, status: "ocupado"},
                  
                ]
            },
            {
                horario: "20:30",
                cadeiras: [
                    {id: 1, status: "livre"},
                    {id: 2, status: "ocupado"},
                    {id: 3, status:"livre"},
                    {id: 4, status: "livre"},
                    {id: 5, status: "livre"},
                    {id: 6, status: "ocupado"},
                    {id: 7, status: "ocupado"},
                    {id: 8, status: "ocupado"},
                    {id: 9, status: "livre"},
                    {id: 10, status: "ocupado"},
                    {id: 11, status: "ocupado"},
                    {id: 12, status: "ocupado"},
                    {id: 13, status: "livre"},
                    {id: 14, status: "livre"},
                    {id: 15, status: "livre"},
                    {id: 16, status: "ocupado"},
                    {id: 17, status: "livre"},
                    {id: 18, status: "livre"},
                    {id: 19, status: "ocupado"},
                    {id: 20, status: "livre"},
                    {id: 21, status: "ocupado"},
                    {id: 22, status: "ocupado"},
                    {id: 23, status: "ocupado"},
                    {id: 24, status: "livre"},
                    {id: 25, status: "livre"},
                    {id: 26, status: "livre"},
                    {id: 27, status: "livre"},
                    {id: 28, status: "livre"},
                    {id: 29, status: "ocupado"},
                    {id: 30, status: "ocupado"},
                    
                ]
            },
            {
                horario: "21:30",
                cadeiras: [
                    {id: 1, status: "livre"},
                    {id: 2, status: "ocupado"},
                    {id: 3, status:"livre"},
                    {id: 4, status: "livre"},
                    {id: 5, status: "livre"},
                    {id: 6, status: "ocupado"},
                    {id: 7, status: "ocupado"},
                    {id: 8, status: "ocupado"},
                    {id: 9, status: "livre"},
                    {id: 10, status: "ocupado"},
                    {id: 11, status: "ocupado"},
                    {id: 12, status: "ocupado"},
                    {id: 13, status: "livre"},
                    {id: 14, status: "livre"},
                    {id: 15, status: "livre"},
                    {id: 16, status: "ocupado"},
                    {id: 17, status: "livre"},
                    {id: 18, status: "livre"},
                    {id: 19, status: "ocupado"},
                    {id: 20, status: "livre"},
                    {id: 21, status: "ocupado"},
                    {id: 22, status: "ocupado"},
                    {id: 23, status: "ocupado"},
                    {id: 24, status: "livre"},
                    {id: 25, status: "livre"},
                    {id: 26, status: "livre"},
                    {id: 27, status: "livre"},
                    {id: 28, status: "livre"},
                    {id: 29, status: "ocupado"},
                    {id: 30, status: "ocupado"},
                    
                ]
            }
        ]
    },
    {
        id:8,
        filme:movies[7],
        cronogramas:[
            {
                horario: "19:00",
                cadeiras: [
                  {id: 1, status: "livre"},
                  {id: 2, status: "ocupado"},
                  {id: 3, status:"livre"},
                  {id: 4, status: "livre"},
                  {id: 5, status: "livre"},
                  {id: 6, status: "ocupado"},
                  {id: 7, status: "ocupado"},
                  {id: 8, status: "ocupado"},
                  {id: 9, status: "livre"},
                  {id: 10, status: "ocupado"},
                  {id: 11, status: "ocupado"},
                  {id: 12, status: "ocupado"},
                  {id: 13, status: "livre"},
                  {id: 14, status: "livre"},
                  {id: 15, status: "livre"},
                  {id: 16, status: "ocupado"},
                  {id: 17, status: "livre"},
                  {id: 18, status: "livre"},
                  {id: 19, status: "ocupado"},
                  {id: 20, status: "livre"},
                  {id: 21, status: "ocupado"},
                  {id: 22, status: "ocupado"},
                  {id: 23, status: "ocupado"},
                  {id: 24, status: "livre"},
                  {id: 25, status: "livre"},
                  {id: 26, status: "livre"},
                  {id: 27, status: "livre"},
                  {id: 28, status: "livre"},
                  {id: 29, status: "ocupado"},
                  {id: 30, status: "ocupado"},
                  
                ]
            },
            {
                horario: "20:30",
                cadeiras: [
                    {id: 1, status: "livre"},
                    {id: 2, status: "ocupado"},
                    {id: 3, status:"livre"},
                    {id: 4, status: "livre"},
                    {id: 5, status: "livre"},
                    {id: 6, status: "ocupado"},
                    {id: 7, status: "ocupado"},
                    {id: 8, status: "ocupado"},
                    {id: 9, status: "livre"},
                    {id: 10, status: "ocupado"},
                    {id: 11, status: "ocupado"},
                    {id: 12, status: "ocupado"},
                    {id: 13, status: "livre"},
                    {id: 14, status: "livre"},
                    {id: 15, status: "livre"},
                    {id: 16, status: "ocupado"},
                    {id: 17, status: "livre"},
                    {id: 18, status: "livre"},
                    {id: 19, status: "ocupado"},
                    {id: 20, status: "livre"},
                    {id: 21, status: "ocupado"},
                    {id: 22, status: "ocupado"},
                    {id: 23, status: "ocupado"},
                    {id: 24, status: "livre"},
                    {id: 25, status: "livre"},
                    {id: 26, status: "livre"},
                    {id: 27, status: "livre"},
                    {id: 28, status: "livre"},
                    {id: 29, status: "ocupado"},
                    {id: 30, status: "ocupado"},
                    
                ]
            },
            {
                horario: "21:30",
                cadeiras: [
                    {id: 1, status: "livre"},
                    {id: 2, status: "ocupado"},
                    {id: 3, status:"livre"},
                    {id: 4, status: "livre"},
                    {id: 5, status: "livre"},
                    {id: 6, status: "ocupado"},
                    {id: 7, status: "ocupado"},
                    {id: 8, status: "ocupado"},
                    {id: 9, status: "livre"},
                    {id: 10, status: "ocupado"},
                    {id: 11, status: "ocupado"},
                    {id: 12, status: "ocupado"},
                    {id: 13, status: "livre"},
                    {id: 14, status: "livre"},
                    {id: 15, status: "livre"},
                    {id: 16, status: "ocupado"},
                    {id: 17, status: "livre"},
                    {id: 18, status: "livre"},
                    {id: 19, status: "ocupado"},
                    {id: 20, status: "livre"},
                    {id: 21, status: "ocupado"},
                    {id: 22, status: "ocupado"},
                    {id: 23, status: "ocupado"},
                    {id: 24, status: "livre"},
                    {id: 25, status: "livre"},
                    {id: 26, status: "livre"},
                    {id: 27, status: "livre"},
                    {id: 28, status: "livre"},
                    {id: 29, status: "ocupado"},
                    {id: 30, status: "ocupado"},
                    
                ]
            }
        ]
    },
    {
        id:9,
        filme:movies[8],
        cronogramas:[
            {
                horario: "19:00",
                cadeiras: [
                  {id: 1, status: "livre"},
                  {id: 2, status: "ocupado"},
                  {id: 3, status:"livre"},
                  {id: 4, status: "livre"},
                  {id: 5, status: "livre"},
                  {id: 6, status: "ocupado"},
                  {id: 7, status: "ocupado"},
                  {id: 8, status: "ocupado"},
                  {id: 9, status: "livre"},
                  {id: 10, status: "ocupado"},
                  {id: 11, status: "ocupado"},
                  {id: 12, status: "ocupado"},
                  {id: 13, status: "livre"},
                  {id: 14, status: "livre"},
                  {id: 15, status: "livre"},
                  {id: 16, status: "ocupado"},
                  {id: 17, status: "livre"},
                  {id: 18, status: "livre"},
                  {id: 19, status: "ocupado"},
                  {id: 20, status: "livre"},
                  {id: 21, status: "ocupado"},
                  {id: 22, status: "ocupado"},
                  {id: 23, status: "ocupado"},
                  {id: 24, status: "livre"},
                  {id: 25, status: "livre"},
                  {id: 26, status: "livre"},
                  {id: 27, status: "livre"},
                  {id: 28, status: "livre"},
                  {id: 29, status: "ocupado"},
                  {id: 30, status: "ocupado"},
                  
                ]
            },
            {
                horario: "20:30",
                cadeiras: [
                    {id: 1, status: "livre"},
                    {id: 2, status: "ocupado"},
                    {id: 3, status:"livre"},
                    {id: 4, status: "livre"},
                    {id: 5, status: "livre"},
                    {id: 6, status: "ocupado"},
                    {id: 7, status: "ocupado"},
                    {id: 8, status: "ocupado"},
                    {id: 9, status: "livre"},
                    {id: 10, status: "ocupado"},
                    {id: 11, status: "ocupado"},
                    {id: 12, status: "ocupado"},
                    {id: 13, status: "livre"},
                    {id: 14, status: "livre"},
                    {id: 15, status: "livre"},
                    {id: 16, status: "ocupado"},
                    {id: 17, status: "livre"},
                    {id: 18, status: "livre"},
                    {id: 19, status: "ocupado"},
                    {id: 20, status: "livre"},
                    {id: 21, status: "ocupado"},
                    {id: 22, status: "ocupado"},
                    {id: 23, status: "ocupado"},
                    {id: 24, status: "livre"},
                    {id: 25, status: "livre"},
                    {id: 26, status: "livre"},
                    {id: 27, status: "livre"},
                    {id: 28, status: "livre"},
                    {id: 29, status: "ocupado"},
                    {id: 30, status: "ocupado"},
                    
                ]
            },
            {
                horario: "21:30",
                cadeiras: [
                    {id: 1, status: "livre"},
                    {id: 2, status: "ocupado"},
                    {id: 3, status:"livre"},
                    {id: 4, status: "livre"},
                    {id: 5, status: "livre"},
                    {id: 6, status: "ocupado"},
                    {id: 7, status: "ocupado"},
                    {id: 8, status: "ocupado"},
                    {id: 9, status: "livre"},
                    {id: 10, status: "ocupado"},
                    {id: 11, status: "ocupado"},
                    {id: 12, status: "ocupado"},
                    {id: 13, status: "livre"},
                    {id: 14, status: "livre"},
                    {id: 15, status: "livre"},
                    {id: 16, status: "ocupado"},
                    {id: 17, status: "livre"},
                    {id: 18, status: "livre"},
                    {id: 19, status: "ocupado"},
                    {id: 20, status: "livre"},
                    {id: 21, status: "ocupado"},
                    {id: 22, status: "ocupado"},
                    {id: 23, status: "ocupado"},
                    {id: 24, status: "livre"},
                    {id: 25, status: "livre"},
                    {id: 26, status: "livre"},
                    {id: 27, status: "livre"},
                    {id: 28, status: "livre"},
                    {id: 29, status: "ocupado"},
                    {id: 30, status: "ocupado"},
                    
                ]
            }
        ]
    },
    {
        id:10,
        filme:movies[9],
        cronogramas:[
            {
                horario: "19:00",
                cadeiras: [
                  {id: 1, status: "livre"},
                  {id: 2, status: "ocupado"},
                  {id: 3, status:"livre"},
                  {id: 4, status: "livre"},
                  {id: 5, status: "livre"},
                  {id: 6, status: "ocupado"},
                  {id: 7, status: "ocupado"},
                  {id: 8, status: "ocupado"},
                  {id: 9, status: "livre"},
                  {id: 10, status: "ocupado"},
                  {id: 11, status: "ocupado"},
                  {id: 12, status: "ocupado"},
                  {id: 13, status: "livre"},
                  {id: 14, status: "livre"},
                  {id: 15, status: "livre"},
                  {id: 16, status: "ocupado"},
                  {id: 17, status: "livre"},
                  {id: 18, status: "livre"},
                  {id: 19, status: "ocupado"},
                  {id: 20, status: "livre"},
                  {id: 21, status: "ocupado"},
                  {id: 22, status: "ocupado"},
                  {id: 23, status: "ocupado"},
                  {id: 24, status: "livre"},
                  {id: 25, status: "livre"},
                  {id: 26, status: "livre"},
                  {id: 27, status: "livre"},
                  {id: 28, status: "livre"},
                  {id: 29, status: "ocupado"},
                  {id: 30, status: "ocupado"},
                  
                ]
            },
            {
                horario: "20:30",
                cadeiras: [
                    {id: 1, status: "livre"},
                    {id: 2, status: "ocupado"},
                    {id: 3, status:"livre"},
                    {id: 4, status: "livre"},
                    {id: 5, status: "livre"},
                    {id: 6, status: "ocupado"},
                    {id: 7, status: "ocupado"},
                    {id: 8, status: "ocupado"},
                    {id: 9, status: "livre"},
                    {id: 10, status: "ocupado"},
                    {id: 11, status: "ocupado"},
                    {id: 12, status: "ocupado"},
                    {id: 13, status: "livre"},
                    {id: 14, status: "livre"},
                    {id: 15, status: "livre"},
                    {id: 16, status: "ocupado"},
                    {id: 17, status: "livre"},
                    {id: 18, status: "livre"},
                    {id: 19, status: "ocupado"},
                    {id: 20, status: "livre"},
                    {id: 21, status: "ocupado"},
                    {id: 22, status: "ocupado"},
                    {id: 23, status: "ocupado"},
                    {id: 24, status: "livre"},
                    {id: 25, status: "livre"},
                    {id: 26, status: "livre"},
                    {id: 27, status: "livre"},
                    {id: 28, status: "livre"},
                    {id: 29, status: "ocupado"},
                    {id: 30, status: "ocupado"},
                    
                ]
            },
            {
                horario: "21:30",
                cadeiras: [
                    {id: 1, status: "livre"},
                    {id: 2, status: "ocupado"},
                    {id: 3, status:"livre"},
                    {id: 4, status: "livre"},
                    {id: 5, status: "livre"},
                    {id: 6, status: "ocupado"},
                    {id: 7, status: "ocupado"},
                    {id: 8, status: "ocupado"},
                    {id: 9, status: "livre"},
                    {id: 10, status: "ocupado"},
                    {id: 11, status: "ocupado"},
                    {id: 12, status: "ocupado"},
                    {id: 13, status: "livre"},
                    {id: 14, status: "livre"},
                    {id: 15, status: "livre"},
                    {id: 16, status: "ocupado"},
                    {id: 17, status: "livre"},
                    {id: 18, status: "livre"},
                    {id: 19, status: "ocupado"},
                    {id: 20, status: "livre"},
                    {id: 21, status: "ocupado"},
                    {id: 22, status: "ocupado"},
                    {id: 23, status: "ocupado"},
                    {id: 24, status: "livre"},
                    {id: 25, status: "livre"},
                    {id: 26, status: "livre"},
                    {id: 27, status: "livre"},
                    {id: 28, status: "livre"},
                    {id: 29, status: "ocupado"},
                    {id: 30, status: "ocupado"},
                    
                ]
            }
        ]
    }
]